### ISSUE TITLE
Not working in GNOME 3.36

### ISSUE THREAD

**Issue by zsdedan** [zykh/walNUT#6]
Extension not working in GNOME 3.36. In logs I see this message:

`Jun 12 12:31:52 amd64 gnome-shell[2732]: JS ERROR: Extension walnut@networkupstools: TypeError: this._construct is not a function#012newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21#012_init@/home/dedan/.local/share/gnome-shell/extensions/walnut@networkupstools/extension.js:1459:14#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012enable@/home/dedan/.local/share/gnome-shell/extensions/walnut@networkupstools/extension.js:5027:11#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:336:26#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:577:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:552:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:586:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:617:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:55:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22#012start@resource:///org/gnome/shell/ui/main.js:146:5#012@<main>:1:47
`

**Comment by tabascoz** [comment]
Hi - same here. Is the project still alive? Would be glad to see it being updated, I do appreciate @zykh!

**Comment by louisvd** [comment]
I would also like this to work on 3.36.  Testing from branch 3.32 also failed.

**Comment by gearhead** [comment]
Would love to see this work. Trying and failing in gnome 3.38.3
