### ISSUE TITLE
Broken in GNOME 3.32

### ISSUE THREAD

**Issue by zman0900** [zykh/walNUT#3]
Extension fails to load with error:

    gnome-shell[6893]: Extension "walnut@networkupstools" had error: TypeError: this._construct is not a function

**Comment by zykh** [comment]
Hi @zman0900 and sorry for the delay, I'm still struggling a bit with my backlog.

My 'compliance' reaction was this:
https://github.com/zykh/walNUT/tree/3.32

...but I haven't had time yet to test it thoroughly (so, at least for the moment, it'll stay out of master).

If you feel adventurous enough, I'd really appreciate your feedback on it.

**Comment by tabascoz** [comment]
this branch is working fine on gentoo 3.30
thanks,

**Comment by zman0900** [comment]
I tried out your branch and it works great.  Only one minor cosmetic issue where when I first open the menu, there is some text overlaying the bottom row of buttons, but it quickly disappears.

**Comment by DanAE111** [comment]
So far so good for me on Arch
